[general]
name = "relu-helion"
license = "Apache-2.0"
backends = [
  "cuda",
]
version = 1
edition = 5
python-depends = ["helion"]

[general.hub]
repo-id = "kernels-community/relu-helion"

[torch-noarch]
