[general]
name = "finegrained-fp8-helion"
license = "Apache-2.0"
backends = [
  "cuda",
]
version = 1
edition = 5
python-depends = ["helion"]

[general.hub]
repo-id = "kernels-community/finegrained-fp8-helion"

[torch-noarch]
