[general]
name = "deformable-detr-helion"
license = "Apache-2.0"
backends = [
  "cuda",
]
version = 1
edition = 5
python-depends = ["helion"]

[general.hub]
repo-id = "kernels-community/deformable-detr-helion"

[torch-noarch]
